name: uBacktest e2e/Workflow Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  WASP_TELEMETRY_DISABLE: 1
  WASP_VERSION: 0.18.1

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the uBacktest monorepo
        uses: actions/checkout@v4
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Install Wasp
        run: |
          curl -sSL https://get.wasp.sh/installer.sh | sh -s -- -v ${{ env.WASP_VERSION }}
      - name: Set ENV Vars to Mock Values
        run: |
          cd app
          cp .env.server.example .env.server && cp .env.client.example .env.client
      - name: Install Node.js Dependencies for Playwright Tests
        run: |
          cd test
          npm ci
      - name: Install Node.js Dependencies for App
        run: |
          cd app
          npm ci
      - name: Set up Playwright
        run: |
          cd test
          npx playwright install --with-deps
      - name: Install Stripe CLI
        run: |
          curl -s https://packages.stripe.dev/api/security/keypair/stripe-cli-gpg/public | gpg --dearmor | sudo tee /usr/share/keyrings/stripe.gpg
          echo "deb [signed-by=/usr/share/keyrings/stripe.gpg] https://packages.stripe.dev/stripe-cli-debian-local stable main" | sudo tee -a /etc/apt/sources.list.d/stripe.list
          sudo apt update
          sudo apt install stripe
      - name: Run Stripe CLI to listen for webhooks
        run: |
          stripe listen --api-key ${{ secrets.TEST_STRIPE_API_KEY }} --forward-to localhost:3001/payments-webhook &
      - name: Run Playwright Tests
        env:
          # server-side vars
          JUDGE_API_KEY_RAPID_API: ${{ secrets.JUDGE_API_KEY_RAPID_API }}
          TIINGO_API_KEY: ${{ secrets.TIINGO_API_KEY }}
          # payment test keys:
          STRIPE_API_KEY: ${{ secrets.TEST_STRIPE_API_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.TEST_STRIPE_WEBHOOK_SECRET }}
          STRIPE_CUSTOMER_PORTAL_URL: ${{ secrets.TEST_STRIPE_CUSTOMER_PORTAL_URL }}
          PAYMENTS_HOBBY_SUBSCRIPTION_PLAN_ID: ${{ secrets.TEST_PAYMENTS_HOBBY_SUBSCRIPTION_PLAN_ID }}
          PAYMENTS_PRO_SUBSCRIPTION_PLAN_ID: ${{ secrets.TEST_PAYMENTS_PRO_SUBSCRIPTION_PLAN_ID }}
          PAYMENTS_CREDITS_5_PLAN_ID: ${{ secrets.TEST_PAYMENTS_CREDITS_5_PLAN_ID }}
          # client-side vars
          SKIP_EMAIL_VERIFICATION_IN_DEV: true
          SKIP_EMAIL_SENDING_IN_DEV: true
          REACT_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_ID }}
        run: |
          cd test
          npm run e2e:playwright

  deploy:
    runs-on: ubuntu-latest
    needs: e2e_tests
    steps:
      - name: Checkout the uBacktest Repository
        uses: actions/checkout@v4

      - name: Install Wasp
        run: |
          curl -sSL https://get.wasp.sh/installer.sh | sh -s -- -v ${{ env.WASP_VERSION }}

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          REACT_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_ID }}
        run: |
          cd app
          wasp deploy fly deploy
